app.title = "Key pad manager"

win.mainTitle = "Device configuration"
win.selDevTitle = "Select device"

card.noDevice = "No device connected"

navi.deviceTitle = "Device"
navi.appsTitle = "Apps"
navi.macrosTitle = "Macros"
navi.scriptTitle = "Scripts"
navi.mappingTitle = "Mappings"
navi.managementTitle = "Management"

apps.selProcTitle = "Select process"
btn.generalCancel = "Cancel"
btn.generalSelect = "Select"
btn.search = "Search..."

try.conDevices = "Connected devices"
try.conDevicesTT = "Show connected devices"
try.selDevice = "Select device"
try.selDeviceTT = "Open device selection"
try.quit = "Quit"
try.quitTT = "Stop application"

cont.pid = "PID:"
cont.vid = "VID:"
cont.product = "Product:"
cont.manufacturer = "Manufacturer:"
cont.serial = "Serial:"
cont.rawDataVal = "Value"
cont.rawDataHex = "Hex"
cont.rawDataDec = "Dec"
cont.rawDataReceived = "Received"
cont.rawDataType = "Type"
cont.buttonTestLabel = "Test"

common.notDefined = "Not defined"