app.title = "Key pad manager"
cont.deviceInfoTitle = "Info"
navi.deviceInfoTitle = "Info"
cont.rawDataTitle = "Raw data"
navi.rawDataTitle = "Raw data"
card.noDevice = "No device connected"
win.mainTitle = "Device configuration"
win.selDevTitle = "Select device"
cont.pid = "PID:"
cont.vid = "VID:"
cont.product = "Product:"
cont.manufacturer = "Manufacturer:"
cont.serial = "Serial:"
navi.deviceSecTitle = "Device"
try.conDevices = "Connected devices"
try.conDevicesTT = "Show connected devices"
try.selDevice = "Select device"
try.selDeviceTT = "Open device selection"
try.quit = "Quit"
try.quitTT = "Stop application"