app.title = "Key pad manager"

win.mainTitle = "Device configuration"
win.selDevTitle = "Select device"

card.noDevice = "No device connected"

navi.deviceInfoTitle = "Info"
navi.rawDataTitle = "Raw data"
navi.deviceBranchTitle = "Device"
navi.profileBranchTitle = "Profile"

try.conDevices = "Connected devices"
try.conDevicesTT = "Show connected devices"
try.selDevice = "Select device"
try.selDeviceTT = "Open device selection"
try.quit = "Quit"
try.quitTT = "Stop application"

cont.deviceInfoTitle = "Info"
cont.rawDataTitle = "Raw data"
cont.pid = "PID:"
cont.vid = "VID:"
cont.product = "Product:"
cont.manufacturer = "Manufacturer:"
cont.serial = "Serial:"
cont.rawDataVal = "Value"
cont.rawDataHex = "Hex"
cont.rawDataDec = "Dec"
cont.rawDataReceived = "Received"
cont.rawDataType = "Type"
cont.rawDataByteNo = "Byte number"
cont.rawBitMask = "Bit mask"
cont.rawDataMin = "Min value"
cont.rawDataMax = "Max value"

common.notDefined = "Not defined"