app.title = "Key pad manager"
cont.deviceInfoTitle = "Informatii controller"
navi.deviceInfoTitle = "Informatii"
cont.rawDataTitle = "Date live"
navi.rawDataTitle = "Date live"
card.noDevice = "Nu sunt controllere conectate"
win.mainTitle = "Configurare controller"
win.selDevTitle = "Selectarie controller"
cont.pid = "PID:"
cont.vid = "VID:"
cont.product = "Produs:"
cont.manufacturer = "Producator:"
cont.serial = "Serial:"
navi.deviceSecTitle = "Controller"
try.conDevices = "Controllere connectate"
try.conDevicesTT = "Afiseaza controllerele conectate"
try.selDevice = "Selecteaza controller"
try.selDeviceTT = "Deschide selectia de controllere"
try.quit = "Iesire"
try.quitTT = "Opreste aplicatia"