app.title = "Key pad manager"

win.mainTitle = "Configurare controller"
win.selDevTitle = "Selectarie controller"

card.noDevice = "Nu sunt controllere conectate"

navi.deviceTitle = "Pad"
navi.appsTitle = "Aplicatii"
navi.macrosTitle = "Macrouri"
navi.scriptTitle = "Scripturi"
navi.mappingTitle = "Mappari"
navi.managementTitle = "Management"

try.conDevices = "Controllere connectate"
try.conDevicesTT = "Afiseaza controllerele conectate"
try.selDevice = "Selecteaza controller"
try.selDeviceTT = "Deschide selectia de controllere"
try.quit = "Iesire"
try.quitTT = "Opreste aplicatia"

cont.pid = "PID:"
cont.vid = "VID:"
cont.product = "Produs:"
cont.manufacturer = "Producator:"
cont.serial = "Serial:"
cont.rawDataVal = "Valoare"
cont.rawDataHex = "Hexa"
cont.rawDataDec = "Decemical"
cont.rawDataReceived = "Primit"
cont.rawDataType = "Tip"
cont.buttonTestLabel = "Test"

common.notDefined = "Nedefinit"