app.title = "Key pad manager"

win.mainTitle = "Configurare controller"
win.selDevTitle = "Selectarie controller"

card.noDevice = "Nu sunt controllere conectate"

navi.deviceInfoTitle = "Informatii"
navi.rawDataTitle = "Date live"
navi.deviceBranchTitle = "Controller"
navi.profileBranchTitle = "Profile"

try.conDevices = "Controllere connectate"
try.conDevicesTT = "Afiseaza controllerele conectate"
try.selDevice = "Selecteaza controller"
try.selDeviceTT = "Deschide selectia de controllere"
try.quit = "Iesire"
try.quitTT = "Opreste aplicatia"

cont.pid = "PID:"
cont.vid = "VID:"
cont.product = "Produs:"
cont.manufacturer = "Producator:"
cont.serial = "Serial:"
cont.rawDataVal = "Valoare"
cont.rawDataHex = "Hexa"
cont.rawDataDec = "Decemical"
cont.rawDataReceived = "Primit"
cont.rawDataType = "Tip"
cont.buttonTestLabel = "Test"

common.notDefined = "Nedefinit"