// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package txt

import "fyne.io/fyne/v2"

var LangEnToml = &fyne.StaticResource{
	StaticName: "en.toml",
	StaticContent: []byte(
		"app.title = \"Key pad manager\"\r\n\r\nwin.mainTitle = \"Device configuration\"\r\nwin.selDevTitle = \"Select device\"\r\n\r\ncard.noDevice = \"No device connected\"\r\n\r\nnavi.deviceTitle = \"Device\"\r\nnavi.appsTitle = \"Apps\"\r\nnavi.macrosTitle = \"Macros\"\r\nnavi.scriptTitle = \"Scripts\"\r\nnavi.mappingTitle = \"Mappings\"\r\nnavi.managementTitle = \"Management\"\r\n\r\nappS.appFileTab = \"App file\"\r\nappS.runningProcessTab = \"App running\"\r\n\r\ntry.conDevices = \"Connected devices\"\r\ntry.conDevicesTT = \"Show connected devices\"\r\ntry.selDevice = \"Select device\"\r\ntry.selDeviceTT = \"Open device selection\"\r\ntry.quit = \"Quit\"\r\ntry.quitTT = \"Stop application\"\r\n\r\ncont.pid = \"PID:\"\r\ncont.vid = \"VID:\"\r\ncont.product = \"Product:\"\r\ncont.manufacturer = \"Manufacturer:\"\r\ncont.serial = \"Serial:\"\r\ncont.rawDataVal = \"Value\"\r\ncont.rawDataHex = \"Hex\"\r\ncont.rawDataDec = \"Dec\"\r\ncont.rawDataReceived = \"Received\"\r\ncont.rawDataType = \"Type\"\r\ncont.buttonTestLabel = \"Test\"\r\n\r\ncommon.notDefined = \"Not defined\""),
}
var LangRoToml = &fyne.StaticResource{
	StaticName: "ro.toml",
	StaticContent: []byte(
		"app.title = \"Key pad manager\"\r\n\r\nwin.mainTitle = \"Configurare controller\"\r\nwin.selDevTitle = \"Selectarie controller\"\r\n\r\ncard.noDevice = \"Nu sunt controllere conectate\"\r\n\r\nnavi.deviceTitle = \"Pad\"\r\nnavi.appsTitle = \"Aplicatii\"\r\nnavi.macrosTitle = \"Macrouri\"\r\nnavi.scriptTitle = \"Scripturi\"\r\nnavi.mappingTitle = \"Mappari\"\r\nnavi.managementTitle = \"Management\"\r\n\r\nappS.appFileTab = \"App file\"\r\nappS.runningProcessTab = \"App running\"\r\n\r\ntry.conDevices = \"Controllere connectate\"\r\ntry.conDevicesTT = \"Afiseaza controllerele conectate\"\r\ntry.selDevice = \"Selecteaza controller\"\r\ntry.selDeviceTT = \"Deschide selectia de controllere\"\r\ntry.quit = \"Iesire\"\r\ntry.quitTT = \"Opreste aplicatia\"\r\n\r\ncont.pid = \"PID:\"\r\ncont.vid = \"VID:\"\r\ncont.product = \"Produs:\"\r\ncont.manufacturer = \"Producator:\"\r\ncont.serial = \"Serial:\"\r\ncont.rawDataVal = \"Valoare\"\r\ncont.rawDataHex = \"Hexa\"\r\ncont.rawDataDec = \"Decemical\"\r\ncont.rawDataReceived = \"Primit\"\r\ncont.rawDataType = \"Tip\"\r\ncont.buttonTestLabel = \"Test\"\r\n\r\ncommon.notDefined = \"Nedefinit\""),
}
