// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package txt

import "fyne.io/fyne/v2"

var LangEnToml = &fyne.StaticResource{
	StaticName: "en.toml",
	StaticContent: []byte(
		"app.title = \"Key pad manager\"\r\ncont.deviceInfoTitle = \"Info\"\r\nnavi.deviceInfoTitle = \"Info\"\r\ncont.rawDataTitle = \"Raw data\"\r\nnavi.rawDataTitle = \"Raw data\"\r\ncard.noDevice = \"No device connected\"\r\nwin.mainTitle = \"Device configuration\"\r\nwin.selDevTitle = \"Select device\"\r\ncont.pid = \"PID:\"\r\ncont.vid = \"VID:\"\r\ncont.product = \"Product:\"\r\ncont.manufacturer = \"Manufacturer:\"\r\ncont.serial = \"Serial:\"\r\nnavi.deviceSecTitle = \"Device\"\r\ntry.conDevices = \"Connected devices\"\r\ntry.conDevicesTT = \"Show connected devices\"\r\ntry.selDevice = \"Select device\"\r\ntry.selDeviceTT = \"Open device selection\"\r\ntry.quit = \"Quit\"\r\ntry.quitTT = \"Stop application\"\r\ncont.rawDataVal = \"Value\"\r\ncont.rawDataHex = \"Hex\"\r\ncont.rawDataDec = \"Dec\"\r\ncont.rawDataReceived = \"Received\"\r\ncont.rawDataType = \"Type\"\r\ncont.rawDataBytePos = \"Byte position\"\r\ncont.rawDataMin = \"Min value\"\r\ncont.rawDataMax = \"Max value\""),
}
var LangRoToml = &fyne.StaticResource{
	StaticName: "ro.toml",
	StaticContent: []byte(
		"app.title = \"Key pad manager\"\r\ncont.deviceInfoTitle = \"Informatii controller\"\r\nnavi.deviceInfoTitle = \"Informatii\"\r\ncont.rawDataTitle = \"Date live\"\r\nnavi.rawDataTitle = \"Date live\"\r\ncard.noDevice = \"Nu sunt controllere conectate\"\r\nwin.mainTitle = \"Configurare controller\"\r\nwin.selDevTitle = \"Selectarie controller\"\r\ncont.pid = \"PID:\"\r\ncont.vid = \"VID:\"\r\ncont.product = \"Produs:\"\r\ncont.manufacturer = \"Producator:\"\r\ncont.serial = \"Serial:\"\r\nnavi.deviceSecTitle = \"Controller\"\r\ntry.conDevices = \"Controllere connectate\"\r\ntry.conDevicesTT = \"Afiseaza controllerele conectate\"\r\ntry.selDevice = \"Selecteaza controller\"\r\ntry.selDeviceTT = \"Deschide selectia de controllere\"\r\ntry.quit = \"Iesire\"\r\ntry.quitTT = \"Opreste aplicatia\"\r\ncont.rawDataVal = \"Valoare\"\r\ncont.rawDataHex = \"Hexa\"\r\ncont.rawDataDec = \"Decemical\"\r\ncont.rawDataReceived = \"Primit\"\r\ncont.rawDataType = \"Tip\"\r\ncont.rawDataBytePos = \"Pozitia byte-ului\"\r\ncont.rawDataMin = \"Valoare minima\"\r\ncont.rawDataMax = \"Valoare maxima\""),
}
