# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Manual trigger

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - run: sudo apt-get install libusb-1.0-0-dev
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Set up setup-msys
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          mingw64/mingw-w64-x86_64-libusb
          mingw64/mingw-w64-x86_64-pkg-config
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
