# Action to create a release for windiws trigger manually
name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: 'v1.0.0'
jobs:
    build-windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.22'
        
        - name: Set up setup-msys
          uses: msys2/setup-msys2@v2
          with:
            install: |-
              mingw64/mingw-w64-x86_64-libusb
              mingw64/mingw-w64-x86_64-pkg-config
        
        - run: echo "D:\a\_temp\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
        - name: Build
          run: go build -v ./...
    
        - name: Test
          run: go test -v ./...

        - uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            files: |
              main.exe
              tag_name: ${{ github.event.inputs.tag }}
              release_name: Release ${{ github.event.inputs.tag }}
            body: |
              manual release
            draft: false
            prerelease: true